# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import re

from pygments.lexers.shell import BashLexer, BashSessionLexer
from pygments.token import Name, Text

# -- Knit-aware highlighting ---------------------------------------------------
#
# Highlight Knit's own API --- the bare word `knit` and any `knit_*` function ---
# with the shell-builtin style (the same one Bash builtins such as `local` and
# `export` get), so calls like `knit_register` or `knit run` stand out in code
# blocks. The regex is anchored so it matches exactly `knit` or
# `knit_<identifier>` and never a lookalike such as `knitting` (a variable) or
# `knit-graph` (a separate binary).

_KNIT_RE = re.compile(r"^knit(_[A-Za-z0-9_]+)?$")


def _knit_promote(tokens):
    """Reclassify Knit API words to the shell-builtin token, leaving strings and
    comments (where `knit_*` names appear as prose) untouched."""
    for index, token, value in tokens:
        if (token in Text or token in Name) and _KNIT_RE.match(value):
            token = Name.Builtin
        yield index, token, value


class KnitBashLexer(BashLexer):
    """BashLexer that renders the Knit API as shell builtins (code blocks)."""

    name = "KnitBash"
    aliases = ["bash"]

    def get_tokens_unprocessed(self, text):
        yield from _knit_promote(super().get_tokens_unprocessed(text))


class KnitBashSessionLexer(BashSessionLexer):
    """Bash session lexer that renders the Knit API as shell builtins (console
    blocks); its inner command lexer is the Knit-aware one above."""

    name = "KnitConsole"
    aliases = ["console"]
    _innerLexerCls = KnitBashLexer


# -- Project information ------------------------------------------------------

project = "Knit"
copyright = "2026, Matthieu Dorier"
author = "Matthieu Dorier"

# -- General configuration ----------------------------------------------------

extensions = [
    "breathe",
    "sphinx_copybutton",
]

templates_path = ["_templates"]
# Stitch Guide recipe fragments (docs/source/stitch/recipes/) are heading-less
# and inlined into the generated per-category pages via `.. include::`; exclude
# them so Sphinx does not also build each as a standalone (orphan) document.
exclude_patterns = ["stitch/recipes/**"]

# -- sphinx-copybutton --------------------------------------------------------
#
# Console blocks (`code-block:: console`) use a "$ " prompt with command output
# interleaved. Strip the prompt on copy and, since the prompt is present, copy
# only the prompted command lines --- never the surrounding output
# (copybutton_only_copy_prompt_lines defaults to True). Multi-line commands are
# written with a trailing "\", so keep those continuation lines when copying.
# Code blocks without a prompt (e.g. `bash` snippets) are copied verbatim.
copybutton_prompt_text = r"\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

pygments_style = 'knit-light'
pygments_dark_style = 'knit-dark'

# -- Options for HTML output --------------------------------------------------

html_theme = "sphinx_book_theme"
html_title = "Knit"
# Shown at the top of the sidebar (the table-of-contents column) and used as the
# browser-tab / favicon icon. Paths are relative to this conf.py.
html_logo = "_static/knit-logo-simple.svg"
html_favicon = "_static/knit-logo-simple.svg"
# The documentation is served under /docs of the knit.sh site (the landing page
# lives at the root); html_baseurl makes canonical links reflect that location.
html_baseurl = "https://knit.sh/docs/"
html_static_path = ["_static"]
html_css_files = ["custom.css"]

html_theme_options = {
    "repository_url": "https://github.com/knit-sh/knit",
    "use_repository_button": True,
    "use_issues_button": True,
    "home_page_in_toc": True,
    # sphinx-book-theme (via pydata-sphinx-theme) generates its own light/dark
    # code highlighting from these options and ignores the top-level
    # pygments_style / pygments_dark_style, so the styles must be set here too.
    "pygments_light_style": "knit-light",
    "pygments_dark_style": "knit-dark",
}

# -- Breathe (Doxygen integration) --------------------------------------------
#
# Doxygen XML is generated by `make docs` into docs/doxygen/xml (see Doxyfile,
# OUTPUT_DIRECTORY = docs/doxygen, GENERATE_XML = YES). The path below is
# resolved relative to this conf.py so the build works regardless of the
# current working directory.

_here = os.path.dirname(os.path.realpath(__file__))

breathe_projects = {
    "knit": os.path.join(_here, "..", "doxygen", "xml"),
}
breathe_default_project = "knit"

# Knit is Bash, but the Doxyfile maps the .sh extension to the C parser
# (EXTENSION_MAPPING = sh=C), so breathe must render its symbols using the C
# domain rather than guessing from the file extension.
breathe_domain_by_extension = {
    "sh": "c",
}

# -- Setup --------------------------------------------------------------------


def _mark_home_page(app, pagename, templatename, context, doctree):
    # Expose an `is_home` flag to the templates. `_templates/layout.html` uses it
    # to drop the " — Knit" browser-tab suffix on the root document only (whose
    # own title is already "Knit"), while every other page keeps "<page> — Knit".
    context["is_home"] = pagename == app.config.root_doc


def setup(app):
    # Override the built-in `bash` and `console` lexers with the Knit-aware
    # variants so `knit` / `knit_*` are highlighted as shell builtins everywhere.
    app.add_lexer("bash", KnitBashLexer)
    app.add_lexer("console", KnitBashSessionLexer)
    app.connect("html-page-context", _mark_home_page)
