# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os

# -- Project information ------------------------------------------------------

project = "Knit"
copyright = "2026, Matthieu Dorier"
author = "Matthieu Dorier"

# -- General configuration ----------------------------------------------------

extensions = [
    "breathe",
]

templates_path = ["_templates"]
exclude_patterns = []

pygments_style = 'emacs'
pygments_dark_style = 'one-dark'

# -- Options for HTML output --------------------------------------------------

html_theme = "sphinx_book_theme"
html_title = "Knit"
html_static_path = ["_static"]

html_theme_options = {
    "repository_url": "https://github.com/knit-sh/knit",
    "use_repository_button": True,
    "use_issues_button": True,
    "home_page_in_toc": True,
}

# -- Breathe (Doxygen integration) --------------------------------------------
#
# Doxygen XML is generated by `make docs` into docs/doxygen/xml (see Doxyfile,
# OUTPUT_DIRECTORY = docs/doxygen, GENERATE_XML = YES). The path below is
# resolved relative to this conf.py so the build works regardless of the
# current working directory.

_here = os.path.dirname(os.path.realpath(__file__))

breathe_projects = {
    "knit": os.path.join(_here, "..", "doxygen", "xml"),
}
breathe_default_project = "knit"

# Knit is Bash, but the Doxyfile maps the .sh extension to the C parser
# (EXTENSION_MAPPING = sh=C), so breathe must render its symbols using the C
# domain rather than guessing from the file extension.
breathe_domain_by_extension = {
    "sh": "c",
}
