#!/bin/bash

## @file setup.sh

# ------------------------------------------------------------------------------
# @var _KNIT_SETUPS
#
# Associative array mapping registered setup names to 1. Used to validate that
# a setup name passed to `knit setup` is known.
# ------------------------------------------------------------------------------
declare -A _KNIT_SETUPS

knit_register __knit_setup "setup" "Setup an environment"
knit_with_required "path:path" "Path to the setup"
knit_with_extra "User-provided setup command to execute"
knit_with_subcommand_title "Setups"
# ------------------------------------------------------------------------------
# @fn __knit_setup()
#
# Entry point for the `setup` CLI command. Creates a directory at the given
# path, exports `KNIT_SETUP_PREFIX` to that directory, invokes the named setup
# subcommand inside it, and saves the resulting environment to
# `$KNIT_SETUP_PREFIX/.activate.sh`. Removes the directory and fatals on
# failure.
#
# Usage:
# ```
# ./exp.sh setup --path </path/to/setup> -- <setup-name> [args...]
# ```
# ------------------------------------------------------------------------------
__knit_setup() {
    local path
    path=$(knit_get_parameter "path" "$@")

    # Extract extra args (after --)
    local args=("$@")
    local extra_index
    extra_index=$(knit_extra_index "${args[@]}")
    local extra=("${args[@]:extra_index}")

    if [[ ${#extra[@]} -eq 0 ]]; then
        knit_fatal "setup requires a setup name (pass it after --)."
    fi

    local setup_name="${extra[0]}"
    local setup_args=("${extra[@]:1}")

    # Check path does not already exist
    if [[ -e "${path}" ]]; then
        knit_fatal "Path \"${path}\" already exists."
    fi

    # Check setup name is registered
    if [[ ! -v _KNIT_SETUPS["${setup_name}"] ]]; then
        knit_fatal "Unknown setup \"${setup_name}\"."
    fi

    # Validate args for the setup subcommand (knit_fatal on bad args)
    local subcmd
    subcmd=$(__knit_command_mangle "setup:${setup_name}")
    _knit_check_command_arguments "${subcmd}" "${setup_args[@]}"

    # Create directory and enter it
    mkdir -p "${path}"
    knit_pushd "${path}"

    # Export KNIT_SETUP_PREFIX so setup functions and callbacks can read it
    export KNIT_SETUP_PREFIX="${PWD}"

    # Invoke the setup subcommand and capture its return value
    local ret=0
    _knit_invoke_command "setup" "${setup_name}" "${setup_args[@]}" || ret=$?

    knit_popd

    # Clean up on failure
    if [[ "${ret}" -ne 0 ]]; then
        rm -rf "${path}"
        knit_fatal "Setup \"${setup_name}\" failed; removed \"${path}\"."
    fi
}
knit_done

# ------------------------------------------------------------------------------
# @fn __knit_setup_before_cb()
#
# Before-callback installed on every setup subcommand by knit_register_setup.
# Verifies that KNIT_SETUP_PREFIX is set, ensuring the setup was invoked
# through `knit setup` rather than called directly.
# ------------------------------------------------------------------------------
__knit_setup_before_cb() {
    if [[ ! -v KNIT_SETUP_PREFIX ]]; then
        knit_fatal "Setup commands must be invoked via \"knit setup\", not directly."
    fi
}

# ------------------------------------------------------------------------------
# @fn __knit_setup_after_cb()
#
# After-callback installed on every setup subcommand by knit_register_setup.
# Dumps all exported environment variables into
# `$KNIT_SETUP_PREFIX/.activate.sh` so that jobs depending on this setup can
# source that file to reproduce the build environment.
#
# Dynamic bash internals (BASH_*, SHLVL, _, OLDPWD, PPID, RANDOM, LINENO,
# SECONDS, KNIT_SETUP_PREFIX) are excluded from the dump.
# ------------------------------------------------------------------------------
__knit_setup_after_cb() {
    local activate="${KNIT_SETUP_PREFIX}/.activate.sh"
    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by knit\n'
        local var
        while IFS= read -r var; do
            case "${var}" in
                BASH_*|SHLVL|_|OLDPWD|PPID|RANDOM|LINENO|SECONDS|KNIT_SETUP_PREFIX)
                    continue ;;
            esac
            printf 'export %s=%s\n' "${var}" "$(printf '%q' "${!var}")"
        done < <(compgen -e)
    } > "${activate}"
    chmod +x "${activate}"
}

# ------------------------------------------------------------------------------
# @fn knit_register_setup()
#
# Register a setup, i.e. a subcommand of the "setup" command that builds
# software and records the resulting environment. The setup is automatically
# backed by a database table named "setup:<name>". A before-callback checks
# that KNIT_SETUP_PREFIX is set; an after-callback saves the environment to
# `$KNIT_SETUP_PREFIX/.activate.sh`.
#
# A call to this function must be followed by any knit_with_* declarations,
# the definition of <fn>, and a call to knit_done.
#
# @param name        Short name for the setup (used as the subcommand name).
# @param fn          Name of the Bash function implementing the setup.
# @param description One-line description shown in `--help`.
#
# Example:
# ```
# knit_register_setup "hello" "hello_fn" "Builds the hello program."
# knit_with_optional "version:string" "main" "Branch or tag to check out."
# hello_fn() {
#   ...
# }
# knit_done
# ```
# ------------------------------------------------------------------------------
knit_register_setup() {
    local name="$1"
    local fn="$2"
    local description="$3"
    knit_register "${fn}" "setup:${name}" "${description}"
    knit_with_table
    _KNIT_SETUPS["${name}"]=1
    _knit_run_before __knit_setup_before_cb
    _knit_run_after  __knit_setup_after_cb
}
