#!/bin/bash

## @file setup.sh

# ------------------------------------------------------------------------------
# @var _KNIT_SETUPS
#
# Associative array mapping registered setup names to 1. Used to validate that
# a setup name passed to `knit setup` is known.
# ------------------------------------------------------------------------------
declare -A _KNIT_SETUPS

knit_register _knit_setup "setup" "Setup an environment"
knit_with_required "path:path" "Path to the setup"
knit_with_dispatch "setup" "User-provided setup command to execute"
knit_with_subcommand_title "Setups"
# ------------------------------------------------------------------------------
# @fn _knit_setup()
#
# Entry point for the `setup` CLI command. Creates a directory at the given
# path, exports `KNIT_SETUP_PREFIX` to that directory, invokes the named setup
# subcommand inside it, and saves the resulting environment to
# `$KNIT_SETUP_PREFIX/.activate.sh`. On success the setup name is also recorded
# in `$KNIT_SETUP_PREFIX/.setup.type` so `knit submit` can validate a job's
# knit_with_setup requirement. Removes the directory and fatals on failure.
#
# Usage:
# ```
# ./exp.sh setup --path </path/to/setup> -- <setup-name> [args...]
# ```
# ------------------------------------------------------------------------------
_knit_setup() {
    local path
    path=$(knit_get_parameter "path" "$@")

    # Extract extra args (after --)
    local args=("$@")
    local extra_index
    extra_index=$(knit_extra_index "${args[@]}")
    local extra=("${args[@]:extra_index}")

    if [[ ${#extra[@]} -eq 0 ]]; then
        knit_fatal "setup requires a setup name (pass it after --)."
    fi

    local setup_name="${extra[0]}"
    local setup_args=("${extra[@]:1}")

    # Check path does not already exist
    if [[ -e "${path}" ]]; then
        knit_fatal "Path \"${path}\" already exists."
    fi

    # Check setup name is registered
    if [[ ! -v _KNIT_SETUPS["${setup_name}"] ]]; then
        knit_fatal "Unknown setup \"${setup_name}\"."
    fi

    # Validate args for the setup subcommand (knit_fatal on bad args)
    local subcmd
    subcmd=$(_knit_command_mangle "setup:${setup_name}")
    _knit_check_command_arguments "${subcmd}" "${setup_args[@]}"

    # Create directory and enter it
    mkdir -p "${path}"
    knit_pushd "${path}"

    # Export KNIT_SETUP_PREFIX so setup functions and callbacks can read it
    export KNIT_SETUP_PREFIX="${PWD}"

    # Invoke the setup subcommand and capture its return value
    local ret=0
    _knit_invoke_command "setup" "${setup_name}" "${setup_args[@]}" || ret=$?

    knit_popd

    # Clean up on failure
    if [[ "${ret}" -ne 0 ]]; then
        rm -rf "${path}"
        knit_fatal "Setup \"${setup_name}\" failed; removed \"${path}\"."
    fi

    # Record the setup type that built this directory so that `knit submit` can
    # check a job's knit_with_setup requirement against it.
    printf '%s\n' "${setup_name}" > "${path}/.setup.type"
}
knit_done

# ------------------------------------------------------------------------------
# @fn _knit_setup_before_cb()
#
# Before-callback installed on every setup subcommand by knit_register_setup.
# Verifies that KNIT_SETUP_PREFIX is set, ensuring the setup was invoked
# through `knit setup` rather than called directly.
# ------------------------------------------------------------------------------
_knit_setup_before_cb() {
    if [[ ! -v KNIT_SETUP_PREFIX ]]; then
        knit_fatal "Setup commands must be invoked via \"knit setup [OPTIONS] -- <setup> [OPTIONS]\", not directly."
    fi
}

# ------------------------------------------------------------------------------
# @fn _knit_setup_after_cb()
#
# After-callback installed on every setup subcommand by knit_register_setup.
# Dumps all exported environment variables into
# `$KNIT_SETUP_PREFIX/.activate.sh` so that jobs depending on this setup can
# source that file to reproduce the build environment.
#
# Dynamic bash internals (BASH_*, SHLVL, _, OLDPWD, PPID, RANDOM, LINENO,
# SECONDS, KNIT_SETUP_PREFIX) are excluded from the dump.
# ------------------------------------------------------------------------------
_knit_setup_after_cb() {
    local activate="${KNIT_SETUP_PREFIX}/.activate.sh"
    {
        printf '#!/usr/bin/env bash\n'
        printf '# Generated by knit\n'
        local var
        while IFS= read -r var; do
            case "${var}" in
                BASH_*|SHLVL|_|OLDPWD|PPID|RANDOM|LINENO|SECONDS|KNIT_SETUP_PREFIX)
                    continue ;;
            esac
            # Skip readonly variables (e.g. KNIT_VERSION): re-exporting them when
            # a job sources .activate.sh fails with "readonly variable".
            local decl flags
            decl="$(declare -p "${var}" 2>/dev/null)"
            flags="${decl#declare -}"
            flags="${flags%% *}"
            [[ "${flags}" == *r* ]] && continue
            printf 'export %s=%s\n' "${var}" "$(printf '%q' "${!var}")"
        done < <(compgen -e)
    } > "${activate}"
    chmod +x "${activate}"
}

# ------------------------------------------------------------------------------
# @fn knit_register_setup()
#
# Register a setup, i.e. a subcommand of the "setup" command that builds
# software and records the resulting environment. The setup is automatically
# backed by a database table named "setup:<name>". A before-callback checks
# that KNIT_SETUP_PREFIX is set; an after-callback saves the environment to
# `$KNIT_SETUP_PREFIX/.activate.sh`.
#
# A call to this function must be followed by any knit_with_* declarations,
# the definition of <fn>, and a call to knit_done.
#
# @param name        Short name for the setup (used as the subcommand name).
# @param fn          Name of the Bash function implementing the setup.
# @param description One-line description shown in `--help`.
#
# Example:
# ```
# knit_register_setup "hello" "hello_fn" "Builds the hello program."
# knit_with_optional "version:string" "main" "Branch or tag to check out."
# hello_fn() {
#   ...
# }
# knit_done
# ```
# ------------------------------------------------------------------------------
knit_register_setup() {
    local name="$1"
    local fn="$2"
    local description="$3"
    knit_register "${fn}" "setup:${name}" "${description}"
    knit_with_table
    _KNIT_SETUPS["${name}"]=1
    _knit_run_before _knit_setup_before_cb
    _knit_run_after  _knit_setup_after_cb
}

# ------------------------------------------------------------------------------
# @fn _knit_setup_spack_env_before_cb()
#
# Before-callback installed by knit_with_spack_env. Runs as the setup's first
# step (before-cbs execute in the setup's own shell, so the activated environment
# persists into the setup body and into the after-callbacks). It materializes the
# environment manifest to ${KNIT_SETUP_PREFIX}/spack.yaml, builds the Spack
# environment at ${KNIT_SETUP_PREFIX}/spack-env, and activates it in the current
# shell so the setup body builds against the installed packages.
#
# The manifest source is captured at registration time and carried in the
# callback arguments (mode + source); trailing arguments are the setup's own
# runtime arguments and are ignored.
#
# @param mode   "file" (source is an absolute path to copy) or "stdin" (source
#               is the literal manifest content captured from a here-doc).
# @param source Manifest path (mode=file) or manifest content (mode=stdin).
# ------------------------------------------------------------------------------
_knit_setup_spack_env_before_cb() {
    local mode="$1"
    local source="$2"
    local yaml="${KNIT_SETUP_PREFIX}/spack.yaml"
    local env_dir="${KNIT_SETUP_PREFIX}/spack-env"
    if [[ "${mode}" == "file" ]]; then
        cp "${source}" "${yaml}"
    else
        printf '%s\n' "${source}" > "${yaml}"
    fi
    _knit_spack_env_install "${env_dir}" "${yaml}"
    # Activate in the setup's own shell so the body sees the packages. The sourced
    # "spack" function (see _knit_spack_exec) performs the activation in-shell.
    _knit_spack_exec env activate -d "${env_dir}"
}

# ------------------------------------------------------------------------------
# @fn _knit_setup_spack_env_after_cb()
#
# After-callback installed by knit_with_spack_env, registered *after* the generic
# _knit_setup_after_cb so it runs last and its appended block is authoritative
# when a job sources .activate.sh. It (1) appends an explicit re-activation block
# to .activate.sh so a job re-activates the exact environment, and (2) records
# the concrete manifest (spack.yaml) and lockfile (spack.lock) as provenance
# outputs, gzip-compressed and base64-encoded.
#
# The provenance is emitted with knit_output: after-callbacks run while the
# command is still on the executing-command stack (it is popped only afterwards),
# so knit_output resolves and type-checks the outputs normally.
#
# Trailing arguments are the setup's runtime arguments and are ignored.
# ------------------------------------------------------------------------------
_knit_setup_spack_env_after_cb() {
    local env_dir="${KNIT_SETUP_PREFIX}/spack-env"
    local activate="${KNIT_SETUP_PREFIX}/.activate.sh"
    {
        printf '\n# Spack environment re-activation (added by knit_with_spack_env)\n'
        printf 'source %q\n' "${_KNIT_SPACK_ROOT}/share/spack/setup-env.sh"
        printf 'spack env activate -d %q\n' "${env_dir}"
    } >> "${activate}"
    if [[ -f "${env_dir}/spack.yaml" ]]; then
        knit_output "__spack_yaml__" "$(gzip -c "${env_dir}/spack.yaml" | base64 -w0)"
    fi
    if [[ -f "${env_dir}/spack.lock" ]]; then
        knit_output "__spack_lock__" "$(gzip -c "${env_dir}/spack.lock" | base64 -w0)"
    fi
}

# ------------------------------------------------------------------------------
# @fn _knit_stdin_is_terminal()
#
# Return success if standard input is an interactive terminal. Factored out of
# knit_with_spack_env so tests can stub it: a real terminal is unavailable under
# bats, so the no-manifest guard cannot be exercised without this seam.
# ------------------------------------------------------------------------------
_knit_stdin_is_terminal() {
    [[ -t 0 ]]
}

# shellcheck disable=SC2120 # public API: often called with no args (stdin form)
# ------------------------------------------------------------------------------
# @fn knit_with_spack_env()
#
# Declare that the setup currently being registered needs a Spack environment,
# built as the setup's first step and inherited by jobs via re-activation. Must
# be called between knit_register_setup and knit_done, at most once per setup
# (also mutually exclusive with knit_with_spack_specs, which funnels through
# here).
#
# The environment is described either by a file (non-empty argument, resolved to
# an absolute path at registration) or, when no argument is given, by a here-doc
# / stdin manifest consumed at registration time. In the no-argument form the
# manifest must actually be redirected: if stdin is an interactive terminal (so
# there is nothing to read) the directive fails fast instead of blocking on
# input, and an empty stdin manifest is likewise rejected. The directive installs
# the
# build/activation callbacks, declares the __spack_yaml__ / __spack_lock__
# provenance outputs (which become columns in the setup's table), advertises the
# requirement in --help, and sets _KNIT_SPACK_REQUIRED so bootstrap
# auto-provisions Spack.
#
# Example:
# ```
# knit_register_setup "libs" "libs_fn" "Build deps with Spack."
# knit_with_spack_env "spack.yaml"          # path form
# # --- or ---
# knit_with_spack_env <<'EOF'               # here-doc form
# spack:
#   specs: [hdf5@1.14, fftw]
#   view: true
# EOF
# libs_fn() { ... }
# knit_done
# ```
#
# @param file Optional path to a spack.yaml manifest. If omitted, the manifest
#             is read from stdin.
# ------------------------------------------------------------------------------
knit_with_spack_env() {
    if [[ ! -v _KNIT_CURRENT_COMMAND ]] \
    || [[ "${_KNIT_CURRENT_COMMAND_DEMANGLED}" != setup:* ]]; then
        knit_fatal "knit_with_spack_env is valid only for setups; it must be called between knit_register_setup and knit_done."
    fi
    _knit_wrapper_reject_declaration "knit_with_spack_env"
    local cmd="${_KNIT_CURRENT_COMMAND}"
    local marker_var="_KNIT_CMD_${cmd}_spack_env"
    if [[ -n "${!marker_var:-}" ]]; then
        knit_fatal "A setup may declare at most one Spack environment (knit_with_spack_env / knit_with_spack_specs)."
    fi
    printf -v "${marker_var}" '%s' '1'

    local mode source
    if [[ -n "$1" ]]; then
        mode="file"
        source="$(realpath -m "$1" 2>/dev/null || printf '%s' "$1")"
    else
        # No path given: the manifest must arrive on stdin (here-doc, here-string,
        # or pipe). If stdin is an interactive terminal there is nothing to read
        # and "cat" would block forever, so fail fast with guidance rather than
        # hang.
        if _knit_stdin_is_terminal; then
            knit_fatal "knit_with_spack_env: no manifest provided. Give a spack.yaml path, feed one on stdin (here-doc/here-string/pipe), or use knit_with_spack_specs."
        fi
        mode="stdin"
        source="$(cat)"
        if [[ -z "${source//[[:space:]]/}" ]]; then
            knit_fatal "knit_with_spack_env: the manifest read from stdin is empty."
        fi
    fi

    _knit_run_before _knit_setup_spack_env_before_cb "${mode}" "${source}"
    _knit_run_after  _knit_setup_spack_env_after_cb

    knit_with_output "__spack_yaml__:string" "" \
        "gzip+base64 of the environment's concrete spack.yaml manifest."
    knit_with_output "__spack_lock__:string" "" \
        "gzip+base64 of the environment's spack.lock lockfile."

    local -n _notes_ref="_KNIT_CMD_${cmd}_notes"
    _notes_ref+=("Builds a Spack environment before the setup body runs.")
    _KNIT_SPACK_REQUIRED="1"
}

# ------------------------------------------------------------------------------
# @fn knit_with_spack_specs()
#
# Lightweight sugar over knit_with_spack_env for the common "just install these
# specs" case: it synthesizes a minimal spack.yaml (the given specs plus
# "view: true") and feeds it to knit_with_spack_env, so provenance capture,
# activation, and auto-provisioning all apply identically. Must be called between
# knit_register_setup and knit_done, and is mutually exclusive with
# knit_with_spack_env on one setup.
#
# Example:
# ```
# knit_register_setup "libs" "libs_fn" "Build deps."
# knit_with_spack_specs "hdf5@1.14" "fftw" "boost"
# libs_fn() { ... }
# knit_done
# ```
#
# @param ... One or more Spack specs.
# ------------------------------------------------------------------------------
knit_with_spack_specs() {
    if [[ ! -v _KNIT_CURRENT_COMMAND ]] \
    || [[ "${_KNIT_CURRENT_COMMAND_DEMANGLED}" != setup:* ]]; then
        knit_fatal "knit_with_spack_specs is valid only for setups; it must be called between knit_register_setup and knit_done."
    fi
    if [[ $# -eq 0 ]]; then
        knit_fatal "knit_with_spack_specs requires at least one spec."
    fi
    local yaml spec
    yaml=$'spack:\n  specs:\n'
    for spec in "$@"; do
        yaml+="    - ${spec}"$'\n'
    done
    yaml+=$'  view: true\n'
    # shellcheck disable=SC2119 # intentional stdin form: manifest fed via here-string
    knit_with_spack_env <<< "${yaml}"
}
